
const artifacts = [
  {
    id: 1,
    position: [30, 0, -160],
    title: "Doomed Family",
    artist: "Dominador Castañedo",
    image: "/images3/1.png", 
  },
  {
    id: 2,
    position: [-20, 0, -140],
    title: "Ravaged Manila",
    artist: "Dominador Castañedo",
    image: "/images3/2.png",
  },
  {
    id: 3,
    position: [-50, 0, -120],
    title: "Rape and Massacre in Ermita",
    artist: "Diosdado M. Lorenzo",
    image: "/images3/3.png",
  },
  {
    id: 4,
    position: [-80, 0, -100],
    title: "Japanese Atrocitees",
    artist: "Manuel Antonio Rodriguez, Sr.",
    image: "/images3/4.png",
  },
  {
    id: 5,
    position: [-100, -10, -80],
    title: "Landing of the Liberation Fortes in Lingayen",
    artist: "Eduardo Perrenoud",
    image: "/images3/5.png",
  },
  {
    id: 6,
    position: [-110, 20, -60],
    title: "The Leyte Landing",
    artist: "Romeo V. Tabuena",
    image: "/images3/6.png",
  },
  {
    id: 7,
    position: [-120, -30, -30],
    title: "The Burning of Manila",
    artist: "Fernando Amorsolo Y Cueto",
    image: "/images3/7.png",
  },
  {
    id: 8,
    position: [-190, -40, 80],
    title: "Bataan",
    artist: "Fernando Amorsolo Y Cueto",
    image: "/images3/8.png",
  },
  {
    id: 9,
    position: [-170, -10, 120],
    title: "Evacuation",
    artist: "Oscar Espiritu",
    image: "/images3/9.png",
  },
  {
    id: 10,
    position: [-10, -40, 900],
    title: "A traggic Lesson (The Fall of Bataan)",
    artist: "Gene Cabrera",
    image: "/images3/10.png",
  },
  {
    id: 11,
    position: [180, -100, 700],
    title: "Bataan Death Marcher",
    artist: "Gene Cabrera",
    image: "/images3/11.png",
  },
  {
    id: 12,
    position: [180, -30, 400],
    title: "Graveyard Scene",
    artist: "Carlos Valino, Jr.",
    image: "/images3/12.png",
  },
  {
    id: 13,
    position: [220, -30, 250],
    title: "Capas",
    artist: "Demetrio Diego",
    image: "/images3/13.png",
  },
  {
    id: 14,
    position: [240, -10, 100],
    title: "Mealtime at the Prison Camp",
    artist: "Wenceslao S. Garcia",
    image: "/images3/14.png",
  },
  {
    id: 15,
    position: [500, -50, -250],
    title: "Death March",
    artist: "Dominador Castañedo",
    image: "/images3/15.png",
  },
];

export default artifacts;
